### ISSUE TITLE
Release v1.2 to Hex?

### ISSUE THREAD

**Issue by taylorzr** [manopapad/proper#146]
Similar to https://github.com/manopapad/proper/issues/114, which was resolved by tagging v1.2. But hex only has v1.1. Can you release v1.2 to hex?

Screenshot of hex:
![screen shot 2017-05-03 at 1 19 39 pm](https://cloud.githubusercontent.com/assets/108883/25676059/4df9abb6-3006-11e7-9f0c-31079bf82654.png)

**Comment by kostis** [comment]
We never put PropEr to hex so we were unaware of that fact...  Shouldn't this request go to `tsharju` instead?  (I have no idea whether/how we can actually update the package there since none of the PropEr maintainer is an owner...)

**Comment by taylorzr** [comment]
Weird, I emailed this tsharju guy. Asked him to update hex, or give you guys access.

**Comment by tsharju** [comment]
Ah. Hello, it's me. :) I put proper to hex.pm some time back since I needed it for a project I was working on. I will update the package asap. Really sorry. Have been extremely busy lately and sort of missed this.

**Comment by tsharju** [comment]
It's there. I needed to modify the `proper.app.src` version number since hex.pm requires semantic versioning. So the version needs to be `1.2.0` instead of `1.2`. If it would be ok I could make a pull request for a `mix.exs` config file to be included in this repository? Also, if needed, I could try to transfer the proper package in hex.pm to someone else. Oh, and let me know if there are any issues with the package in hex.pm. Didn't have time to test it too much.

**Comment by kostis** [comment]
> If it would be ok I could make a pull request for a mix.exs config file to be included in this repository?

Yes, please do.  Thanks for your time and help.

> Also, if needed, I could try to transfer the proper package in hex.pm to someone else.

It's not really needed as long as you take care of things, but perhaps having more owners may avoid long delays in the future.

**Comment by taylorzr** [comment]
Thanks guys, that was super quick!

**Comment by kostis** [comment]
I will close this issue now.  @tsharju : looking forward to the `mix.exs` pull request.
