### ISSUE TITLE
Rebar compile fails when trying to install chicago boss

### ISSUE THREAD

**Issue by jigs2410** [manopapad/proper#99]
==> proper (compile)
INFO:  sh info:
        cwd: "/home/erlangdeveloper/ChicagoBoss-0.8.14/deps/proper"
        cmd: make include/compile_flags.hrl
sh: 1: exec: make: not found
ERROR: Command [compile] failed!

I dont see compile_flags.hrl under include folder. Please advise if i am missing any steps.

**Comment by kostis** [comment]
Can you try to see if you can compile proper as a stand-alone tool and, if not, what error you get then? Otherwise I think that the error is most likely caused by how PropEr was added as a dependency on ChicagoBoss.

Also, note that, for better or worse, PropEr comes with its own rebar script -- which should be used to build PropEr.

**Comment by jigs2410** [comment]
It worked when i got proper by itself. thanks
